### ISSUE TITLE
Add documentation explaining the contents of files under /etc/ssh/auth_principals

### ISSUE THREAD

**Issue by neutralinsomniac** [millotpg/Sheriff#1]
I assume this is just a list of LDAP group names? Separated by newlines? commas? spaces?

**Comment by millotpg** [comment]
Yes. The list of group names separated by back slashes. You can see it implemented here:

https://code.facebook.com/posts/365787980419535/scalable-and-secure-access-with-ssh/

where they "Populate the principals file: 
echo -e 'zone-webservers\nroot-everywhere' > /etc/ssh/auth_principals/root"

The documentation was updated accordingly
